services:
  postgres:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_DB: competitions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_SSL: "off" # Disable SSL
    ports:
      - "5432:5432"
    volumes:
      - pg_ask_data:/var/lib/postgresql/data

volumes:
  pg_ask_data:
